config/routes.rb
Rails.application.routes.draw do
  root to: 'profiles#index'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
    }
    
  resources :profiles, only: [:new, :create, :edit, :update]
  resources :fish_names, only: [:create, :show, :edit, :update, :destroy] do
    resources :fish_infos, only: [:new, :create, :edit, :update, :destroy]
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_one_attached :image

  validates :career, format: { with: /\A[0-9]+\z/ }
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:edit, :update]

  def index
    @profile = current_user.profile
    @fish_names = current_user.fish_names.all.order("fish_kind ASC")
  end

  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(profile_params)
    if @profile.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @profile.update(profile_params)
      redirect_to root_path
    else 
      render :edit 
    end
  end

  private

  def set_profile
    @profile = Profile.find(params[:id])
  end

  def profile_params
    params.require(:profile).permit(:field, :text, :image, :career).merge(user_id: current_user.id)
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_profile_position.html.erb
<div class="profile-image">
  <% if @profile.image.present? %>
    <%= image_tag @profile.image,class:"image" %>
    <%= link_to "プロフィール編集", edit_profile_path(@profile.id), method: :get, class: "profile-edit" %>
  <% else %>
    <%= image_tag "no_image.png",class:"image" %>
    <%= link_to "プロフィール編集", edit_profile_path(@profile.id), method: :get, class: "profile-edit" %>
  <% end %>
</div>

<div class="nickname">
  <%= @profile.user.nickname %>
</div>

<div class="info">
  <table class="profile-table">
    <tr class="profile-tr">
      <th class="profile-th">釣り歴</th>
      <td class="profile-td"><%= @profile.career %>年</td>
    </tr>
    <tr class="profile-tr">
      <th class="profile-th">主な釣り場</th>
      <td class="profile-td"><%= @profile.field %></td>
    </tr>
    <tr class="profile-tr">
      <th class="profile-th">自己紹介</th>
      <td class="profile-td"><%= @profile.text %></td>
    </tr>
  </table>
</div>

app/views/profiles/_ranking_position.html.erb
<h1>ランキング</h1>

app/views/profiles/edit.html.erb
<h2>プロフィール編集</h2>

<%= form_with model: @profile, local: true do |f|%>
  <div class="field">
    <%= f.label :image, "プロフィール画像" %><br />
    <%= f.file_field :image %>
  </div>

  <div class="field">
    <%= f.label :field, "よく行くフィールド" %><br />
    <%= f.text_field :field, placeholder: "例）東京湾、多摩川"  %>
  </div>

  <div class="field">
    <%= f.label :career, "釣り歴" %><br />
    <%= f.text_field :career, placeholder: "年数入力 例）５" %>
  </div>

  <div class="field">
    <%= f.label :text, "自己紹介(100字以内)" %><br />
    <%= f.text_area :text, class: :form__text, maxlength:"100" %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/profiles/index.html.erb
<div class="wrapper">
  <div class="herder">
    <div class="title">
    <h1>釣りすぎ君。</h1>
    </div>
    <div class="out">
    <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %>
    </div>
  </div>
  <div class="profile-position">
    <%= render "profile_position" %>
  </div>
  <div class="body">
    <div class="kinds-position">
      <%= render "fish_names/kinds_position" %>
    </div>
    <div class="ranking-position">
      <%= render "ranking_position" %>
    </div>
  </div>
</div>

app/views/profiles/new.html.erb
<h2>プロフィール登録</h2>

<%= form_with model: @profile, local: true do |f|%>
  <div class="field">
    <%= f.label :image, "プロフィール画像" %><br />
    <%= f.file_field :image %>
  </div>

  <div class="field">
    <%= f.label :field, "よく行くフィールド" %><br />
    <%= f.text_field :field, placeholder: "例）東京湾、多摩川"  %>
  </div>

  <div class="field">
    <%= f.label :career, "釣り歴" %><br />
    <%= f.text_field :career, placeholder: "年数入力 例）５" %>
  </div>

  <div class="field">
    <%= f.label :text, "自己紹介(100字以内)" %><br />
    <%= f.text_area :text, class: :form__text, maxlength:"100" %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>