config/routes.rb
Rails.application.routes.draw do
  root to: 'profiles#index'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
    }
    
  resources :profiles, only: [:new, :create, :edit, :update]
  resources :fish_names, only: [:create, :show, :edit, :update, :destroy] do
    resources :fish_infos, only: [:new, :create, :edit, :update, :destroy]
  end
end

app/models/fish_name.rb
class FishName < ApplicationRecord
  belongs_to :user
  has_many :fish_infos
  has_many :rankings

  validates :fish_kind, presence: true, format: {with: /\A[ァ-ヶー]+\z/}
end

app/controllers/fish_names_controller.rb
class FishNamesController < ApplicationController
  before_action :set_name, except: :create
  
  def create
    @fish_name = FishName.new(name_params)
    if @fish_name.save
      redirect_to root_path
    else 
      redirect_to root_path
    end
  end

  def show
    @fish_infos = @fish_name.fish_infos.includes(:user).order("created_at DESC")
    @total = @fish_name.fish_infos.all.sum(:fish_num)
    @max_size = @fish_name.fish_infos.all.maximum(:fish_size)
  end

  def edit
  end

  def update
    if @fish_name.update(fish_name_params)
      redirect_to root_path
    else 
      render :edit
    end
  end

  def destroy
    @fish_name.destroy
    redirect_to root_path
  end

  private

  def set_name
    @fish_name = FishName.find(params[:id])
  end

  def fish_name_params
    params.require(:fish_name).permit(:fish_kind).merge(user_id: current_user.id)
  end

  def name_params
    params.permit(:fish_kind).merge(user_id: current_user.id)
  end
end

app/helpers/fish_names_helper.rb
module FishNamesHelper
end

app/views/fish_names/_kinds_position.html.erb
  <div>
    <%= form_with model: @fish_name, url: fish_names_path, class: 'form', local: true do |f| %>
    
    <div class="kinds-new">
      <div class="form-input">
        <%= f.text_field :fish_kind, class: 'form-name', placeholder: '魚の名前を登録※カタカナ表記' %>
      </div>
        <%= f.submit '送信', class: 'form-submit' %>
    </div>
    <% end %>
  </div>

  <div >
    <div class="fish-infos">
    <% if @fish_names.present? %>
      <% @fish_names.each do |fish| %>
        <div class="fish-name">
        <%= link_to fish.fish_kind, fish_name_path(fish.id),class: "name-font" %>
        </div>
      <% end %>
    <% end %>
      
    </div>
  </div>

app/views/fish_names/edit.html.erb
<div>
    <%= form_with model: @fish_name, url: fish_name_path(@fish_name.id),  class: 'form', local: true do |f| %>

    <div class="kinds-new">
      <div class="form-input">
        <%= f.text_field :fish_kind, class: 'form-name', placeholder: '魚の名前を登録※カタカナ表記' %>
      </div>
        <%= f.submit '送信', class: 'form-submit' %>
    </div>
    <% end %>
</div>

app/views/fish_names/show.html.erb
<div class="name-title">
  <div>
    <div class="title">
      <%= @fish_name.fish_kind %>
    </div>
  </div>
  <ul class="more_list">
    <% if user_signed_in? && current_user.id == @fish_name.user_id %>
    <li>
      <%= link_to '編集', edit_fish_name_path(@fish_name.id), method: :get %>
    </li>
    <li>
      <%= link_to '削除', fish_name_path(@fish_name.id), method: :delete %>
    </li>
    <% end %>
  </ul>
  <div>
    <table class="fish-info-ta">
      <tr class="fish-info-tr">
        <th class="fish-info-th">総数</th>
        <td class="fish-info-td"><%= @total.to_i %>匹</td>
      </tr>
     </table>
  </div>
  <div>
    <table class="fish-info-ta">
      <tr class="fish-info-tr">
        <th class="fish-info-th">最大サイズ</th>
        <td class="fish-info-td"><%= @max_size %>cm</td>
      </tr>
    </table>
  </div>
  <div class="back-button">
    <a><%= link_to 'ホームに戻る', root_path %></a>
  </div>
</div>

<div>
  <%= link_to "釣果情報を登録する", new_fish_name_fish_info_path(@fish_name.id), method: :get %>
</div>

<div>
  <h3>釣果情報</h3>
  
    <ul class="fish-info">
      <% @fish_infos.each do | fish | %>
          <ul class="more_list">
            <% if user_signed_in? && current_user.id == @fish_name.user_id %>
              <li>
                <%= link_to '編集', edit_fish_name_fish_info_path(@fish_name.id, fish), method: :get %>
              </li>
              <li>
                <%= link_to '削除', fish_name_fish_info_path(@fish_name.id, fish), method: :delete %>
              </li>
            <% end %>
          </ul>
        <table>
          <tbody>
            <tr>
              <th>日付</th>
              <td> <%= fish.day %></td>
            </tr>
            <tr>
              <th colspan="2">
                <%= image_tag fish.image, size: '200x200'%>
              </th>
            </tr>
            <tr>
              <th>最大サイズ</th>
              <td><%= fish.fish_size %></td>
            </tr>
            <tr>
              <th>釣れた数</th>
              <td><%= fish.fish_num %></td>
            </tr>
            <tr>
              <th colspan="2">MEMO</th>
            </tr>
            <tr>
              <td colspan="2"><%= fish.memo %></td>
            </tr>
          </tbody>
        </table>
      <% end %>
    </ul>
</div>