config/routes.rb
Rails.application.routes.draw do
  root to: 'profiles#index'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
    }
    
  resources :profiles, only: [:new, :create, :edit, :update]
  resources :fish_names, only: [:create, :show, :edit, :update, :destroy] do
    resources :fish_infos, only: [:new, :create, :edit, :update, :destroy]
  end
end

app/models/fish_info.rb
class FishInfo < ApplicationRecord
  belongs_to :fish_name
  belongs_to :user
  has_many :rankings
  has_one_attached :image

  with_options presence: true do
    validates :day
    validates :fish_size, format: { with: /\A[0-9]+\z/ }
    validates :fish_num, format: { with: /\A[0-9]+\z/ }
    validates :memo
    validates :fish_name
    validates :user
  end
end

app/controllers/fish_infos_controller.rb
class FishInfosController < ApplicationController
  before_action :set_name_info
  before_action :set_info, except: [:new, :create] 
  
  def new
    @fish_info = FishInfo.new
  end

  def create
    @fish_info = FishInfo.new(info_params)
    if @fish_info.save
      redirect_to fish_name_path(@fish_name)
    else 
      render :new 
    end
  end

  def edit
  end

  def update
    if @fish_info.update(info_params)
      redirect_to fish_name_path(@fish_name)
    else 
      render :edit
    end
  end

  def destroy
    @fish_info.destroy
    redirect_to fish_name_path(@fish_name)
  end

  private

  def set_name_info
    @fish_name = FishName.find(params[:fish_name_id])
  end

  def set_info
    @fish_info = FishInfo.find(params[:id])
  end

  def info_params
    params.require(:fish_info).permit(:day, :image, :fish_size, :fish_num, :memo).merge(user_id: current_user.id, fish_name_id: @fish_name.id)
  end
end

app/helpers/fish_infos_helper.rb
module FishInfosHelper
end

app/views/fish_infos/edit.html.erb
<div class="fish-score">
  <h2>情報を編集</h2>
  <%= form_with model: [@fish_name, @fish_info], url: fish_name_fish_info_path(@fish_name.id),local: true do |f| %>


    <div>
      <div>
        <h5>日付</h5>
        <%= f.date_select :day, use_month_numbers:true %>
      </div>
      <div>
        <h5>写真を選択</h5>
        <%= f.file_field :image %>
      <div>
        <h5>つれた数を入力</h5>
        <%= f.text_field :fish_num, placeholder:"例）10※半角数字"%>匹
      </div>
      <div>
        <h5>最大サイズを入力</h5>
        <%= f.text_field :fish_size, placeholder:"例）23※半角数字"%>cm
      </div>
      <div>
        <h5>MEMO</h5>
        <%= f.text_area :memo %>
      </div>
      <div>
        <%= f.submit "保存する" %>
      </div>
    </div>
  <% end %>
</div>

app/views/fish_infos/new.html.erb
<div class="fish-score">
  <h2>情報を入力</h2>
  <%= form_with model: [@fish_name, @fish_info], url: fish_name_fish_infos_path(@fish_name.id),local: true do |f| %>

    <div>
      <div>
        <h5>日付</h5>
        <%= f.date_select :day, use_month_numbers:true %>
      </div>
      <div>
        <h5>写真を選択</h5>
        <%= f.file_field :image %>
      <div>
        <h5>つれた数を入力</h5>
        <%= f.text_field :fish_num, placeholder:"例）10※半角数字"%>匹
      </div>
      <div>
        <h5>最大サイズを入力</h5>
        <%= f.text_field :fish_size, placeholder:"例）23※半角数字"%>cm
      </div>
      <div>
        <h5>MEMO</h5>
        <%= f.text_area :memo %>
      </div>
      <div>
        <%= f.submit "保存する" %>
      </div>
    </div>
  <% end %>
</div>